# Generated by Django 5.0.6 on 2026-07-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'В сети'), ('dnd', 'Не беспокоить'), ('invisible', 'Невидимка')], default='online', max_length=10),
        ),
    ]
