# Generated by Django 5.0.6 on 2026-07-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
