# Generated by Django 5.0.6 on 2026-07-28 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_loginsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRLoginRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ждёт сканирования'), ('scanned', 'Отсканирован, ждёт подтверждения'), ('confirmed', 'Подтверждён'), ('denied', 'Отклонён')], default='pending', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('code', models.CharField(blank=True, default='', max_length=2)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_login_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
