# Generated by Django 5.0.6 on 2026-07-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_bio_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
