# Generated by Django 5.0.6 on 2026-07-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_custom_status_user_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_status_emoji',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
