# Generated by Django 5.0.6 on 2026-07-29 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_custom_status_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='name_color_1',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='name_color_2',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='name_effect',
            field=models.CharField(choices=[('standard', 'Минимализм'), ('gradient', 'Градиент'), ('neon', 'Неон'), ('cartoon', 'Мультфильм'), ('highlight', 'Выделение')], default='standard', max_length=12),
        ),
        migrations.CreateModel(
            name='NameFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='Название (в списке выбора)')),
                ('file', models.FileField(upload_to='name_fonts/', verbose_name='Файл шрифта (woff2/woff/ttf)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_name_fonts', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Шрифт ника',
                'verbose_name_plural': 'Шрифты ника',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='name_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.namefont', verbose_name='Шрифт ника'),
        ),
    ]
