# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_banner_color_user_name_color_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_anim_speed',
            field=models.FloatField(default=1.0),
        ),
    ]
