# Generated by Django 5.0.6 on 2026-07-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_name_anim_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_anim',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_downloadable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_frame',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
