# Generated by Django 5.2.9 on 2026-08-12 02:39

import accounts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_avatar_anim_user_avatar_downloadable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_sound',
            field=models.CharField(choices=[('default', 'Стандартный'), ('none', 'Без звука'), ('blip', 'Короткий сигнал'), ('chime', 'Колокольчик'), ('pop', 'Хлопок'), ('rise', 'Восходящий'), ('custom', 'Свой файл')], default='default', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='join_sound_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='join_sound_file',
            field=models.FileField(blank=True, max_length=300, upload_to=accounts.models.join_sound_upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='join_sound_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
