# Generated by Django 5.0.6 on 2026-09-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_leave_sound_user_leave_sound_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namefont',
            name='size_adjust',
            field=models.PositiveIntegerField(default=100, help_text='100 — как есть. Увеличьте для мелких/тонких шрифтов (например, рукописных).', verbose_name='Масштаб (% от номинального размера)'),
        ),
    ]
