from django.urls import path

from . import views

urlpatterns = [
    path("config", views.config_view, name="config"),
    path("permissions", views.permissions_catalog_view, name="permissions-catalog"),

    # Загрузка вложения — отдельно от отправки сообщения, см. AttachmentUpload.
    path("attachments", views.AttachmentUpload.as_view(), name="attachment-upload"),

    # Кастомные эмодзи. /api/emoji — все мои наборы разом (и ?ids= для
    # метаданных чужих, см. MyEmoji); управление — внутри своего сервера.
    path("emoji", views.MyEmoji.as_view(), name="my-emoji"),

    # Стикеры. /api/stickers — все доступные наборы (базовые + моих серверов),
    # ?ids= — метаданные конкретных, см. MyStickers.
    path("stickers", views.MyStickers.as_view(), name="my-stickers"),

    path("servers", views.ServerListCreate.as_view(), name="server-list"),
    path("servers/discover", views.ServerDiscover.as_view(), name="server-discover"),
    path("servers/<int:server_id>", views.ServerDetail.as_view(), name="server-detail"),
    path("servers/<int:server_id>/join", views.ServerJoin.as_view(), name="server-join"),
    path("servers/<int:server_id>/leave", views.ServerLeave.as_view(), name="server-leave"),
    path("servers/<int:server_id>/settings",
         views.MyServerSettings.as_view(), name="server-my-settings"),
    path("servers/<int:server_id>/invites",
         views.ServerInvites.as_view(), name="server-invites"),
    path("servers/<int:server_id>/invite-link",
         views.ServerInviteLink.as_view(), name="server-invite-link"),
    path("servers/<int:server_id>/invite-links",
         views.ServerInviteLinksList.as_view(), name="server-invite-links"),
    path("servers/<int:server_id>/members",
         views.ServerMembers.as_view(), name="server-members"),
    path("servers/<int:server_id>/members/<int:user_id>",
         views.ServerMemberDetail.as_view(), name="server-member-detail"),
    path("servers/<int:server_id>/members/<int:user_id>/nickname",
         views.ServerMemberNickname.as_view(), name="server-member-nickname"),
    path("servers/<int:server_id>/channels",
         views.ChannelCreate.as_view(), name="channel-create"),

    path("servers/<int:server_id>/emoji", views.ServerEmojiList.as_view(),
         name="server-emoji"),
    path("servers/<int:server_id>/emoji/<int:emoji_id>",
         views.ServerEmojiDetail.as_view(), name="server-emoji-detail"),

    path("servers/<int:server_id>/stickers", views.ServerStickerList.as_view(),
         name="server-stickers"),
    path("servers/<int:server_id>/stickers/<int:sticker_id>",
         views.ServerStickerDetail.as_view(), name="server-sticker-detail"),

    path("servers/<int:server_id>/roles", views.ServerRoles.as_view(),
         name="server-roles"),
    path("servers/<int:server_id>/roles/<int:role_id>",
         views.ServerRoleDetail.as_view(), name="server-role-detail"),
    path("servers/<int:server_id>/requests",
         views.ServerJoinRequests.as_view(), name="server-join-requests"),
    path("servers/<int:server_id>/requests/<int:request_id>",
         views.ServerJoinRequestDecision.as_view(),
         name="server-join-request-decision"),
    path("servers/<int:server_id>/bans", views.ServerBans.as_view(),
         name="server-bans"),
    path("servers/<int:server_id>/bans/<int:user_id>",
         views.ServerBanDetail.as_view(), name="server-ban-detail"),

    path("channels/<int:channel_id>",
         views.ChannelDetail.as_view(), name="channel-detail"),
    path("channels/<int:channel_id>/clone",
         views.ChannelClone.as_view(), name="channel-clone"),
    path("channels/<int:channel_id>/settings",
         views.ChannelMemberSettingsView.as_view(), name="channel-member-settings"),
    path("channels/<int:channel_id>/invites",
         views.ChannelInvitesList.as_view(), name="channel-invites"),
    path("channels/<int:channel_id>/messages",
         views.ChannelMessages.as_view(), name="channel-messages"),
    path("channels/<int:channel_id>/read",
         views.ChannelReadStateView.as_view(), name="channel-read-state"),
    path("channels/<int:channel_id>/pins",
         views.ChannelPins.as_view(), name="channel-pins"),
    path("channels/<int:channel_id>/voice-members",
         views.ChannelVoiceMembers.as_view(), name="channel-voice-members"),
    path("channels/<int:channel_id>/voice-credentials",
         views.VoiceCredentials.as_view(), name="voice-credentials"),

    path("invites", views.MyServerInvites.as_view(), name="my-server-invites"),
    path("invites/preview", views.InvitePreview.as_view(), name="invite-preview"),
    path("invites/redeem",
         views.ServerInviteRedeem.as_view(), name="server-invite-redeem"),
    path("invites/<int:invite_id>",
         views.ServerInviteDecision.as_view(), name="server-invite-decision"),

    path("friends", views.FriendsView.as_view(), name="friends"),
    path("friends/requests", views.FriendRequests.as_view(), name="friend-requests"),
    path("friends/requests/<int:request_id>/accept",
         views.FriendRequestAccept.as_view(), name="friend-request-accept"),
    path("friends/requests/<int:request_id>",
         views.FriendRequestDecline.as_view(), name="friend-request-decline"),
    path("friends/<int:user_id>", views.FriendRemove.as_view(), name="friend-remove"),

    path("people/known", views.KnownPeople.as_view(), name="known-people"),
    path("users/<int:user_id>/profile-card",
         views.UserProfileCard.as_view(), name="user-profile-card"),
    path("users/<int:user_id>/avatar-anim",
         views.UserAvatarAnimation.as_view(), name="user-avatar-anim"),
    path("users/<int:user_id>/note", views.UserNote.as_view(), name="user-note"),
    path("users/<int:user_id>/relation",
         views.UserRelation.as_view(), name="user-relation"),
    path("users/<int:user_id>/nickname",
         views.UserNickname.as_view(), name="user-nickname"),
    path("relations", views.MyRelations.as_view(), name="my-relations"),
    path("nicknames", views.MyNicknames.as_view(), name="my-nicknames"),
    path("presence", views.PresenceView.as_view(), name="presence"),

    path("conversations", views.ConversationListCreate.as_view(), name="conversation-list"),
    path("conversations/<int:conversation_id>",
         views.ConversationDetail.as_view(), name="conversation-detail"),
    path("conversations/<int:conversation_id>/settings",
         views.ConversationSettings.as_view(), name="conversation-settings"),
    path("conversations/<int:conversation_id>/messages",
         views.ConversationMessages.as_view(), name="conversation-messages"),
    path("conversations/<int:conversation_id>/voice-credentials",
         views.ConversationVoiceCredentials.as_view(),
         name="conversation-voice-credentials"),
]
