# Generated by Django 5.0.6 on 2026-07-25 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='access_mode',
            field=models.CharField(choices=[('invite', 'Только по приглашению'), ('request', 'По заявке'), ('public', 'Публичный')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='server',
            name='age_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='banner_gradient',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='server',
            name='banner_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='server',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='server',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#99aab5', max_length=7)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('view_channels', models.BooleanField(default=True)),
                ('manage_channels', models.BooleanField(default=False)),
                ('manage_roles', models.BooleanField(default=False)),
                ('manage_server', models.BooleanField(default=False)),
                ('manage_invites', models.BooleanField(default=False)),
                ('manage_nicknames', models.BooleanField(default=False)),
                ('manage_members', models.BooleanField(default=False)),
                ('send_messages', models.BooleanField(default=True)),
                ('delete_messages', models.BooleanField(default=False)),
                ('mention_everyone', models.BooleanField(default=False)),
                ('speak', models.BooleanField(default=True)),
                ('video', models.BooleanField(default=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='chat.server')),
            ],
            options={
                'ordering': ['-position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='members', to='chat.role'),
        ),
        migrations.CreateModel(
            name='ServerBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_server_bans', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='chat.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'unique_together': {('server', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ServerJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='chat.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'unique_together': {('server', 'user')},
            },
        ),
    ]
