# Generated by Django 5.0.6 on 2026-07-28 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_attachments_and_reactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='allow_dms_from_server',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='ignore_at_here',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='muted_forever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='notification_level',
            field=models.CharField(choices=[('all', 'Все сообщения'), ('mentions', 'Только упоминания'), ('none', 'Ничего')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='suppress_role_mentions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='mention_permission',
            field=models.CharField(choices=[('everyone', 'Все участники сервера'), ('roles', 'Только выбранные роли')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='role',
            name='mentionable_by',
            field=models.ManyToManyField(blank=True, related_name='can_mention', to='chat.role'),
        ),
        migrations.CreateModel(
            name='ServerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('direct', 'Личное приглашение'), ('link', 'Ссылка')], max_length=10)),
                ('code', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_server_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_server_invites', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chat.server')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='serverinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'direct')), fields=('server', 'invited_user'), name='unique_direct_server_invite'),
        ),
        migrations.AddConstraint(
            model_name='serverinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'link')), fields=('code',), name='unique_server_invite_link_code'),
        ),
    ]
