# Generated by Django 5.0.6 on 2026-07-28 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_notifications_mentions_invites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="serverinvite",
            name="unique_direct_server_invite",
        ),
        migrations.AddField(
            model_name="conversationmessage",
            name="server_invite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversation_messages",
                to="chat.serverinvite",
            ),
        ),
        migrations.AddField(
            model_name="serverinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("accepted", "Принято"),
                    ("declined", "Отклонено"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="serverinvite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "direct"), ("status", "pending")),
                fields=("server", "invited_user"),
                name="unique_direct_server_invite",
            ),
        ),
    ]
