# Generated by Django 5.0.6 on 2026-07-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_profilenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_owner_role',
            field=models.BooleanField(default=False),
        ),
    ]
