# Generated by Django 5.0.6 on 2026-07-29 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_role_is_owner_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='serverinvite',
            name='unique_direct_server_invite',
        ),
        migrations.AddField(
            model_name='channel',
            name='status',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='membership',
            name='pinned_channel_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serverinvite',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='chat.channel'),
        ),
        migrations.AddConstraint(
            model_name='serverinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__isnull', True), ('kind', 'direct'), ('status', 'pending')), fields=('server', 'invited_user'), name='unique_direct_server_invite'),
        ),
        migrations.AddConstraint(
            model_name='serverinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__isnull', False), ('kind', 'direct'), ('status', 'pending')), fields=('server', 'invited_user', 'channel'), name='unique_direct_channel_invite'),
        ),
    ]
