# Generated by Django 5.0.6 on 2026-07-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_serverinvite_unique_direct_server_invite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinvite',
            name='uses',
            field=models.PositiveIntegerField(default=0, verbose_name='Использований'),
        ),
    ]
