# Generated by Django 5.0.6 on 2026-07-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_conversationparticipant_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
