# Generated by Django 5.0.7 on 2026-08-01 20:48

from django.db import migrations, models


def carry_over_pin_permission(apps, schema_editor):
    """Закрепление сообщений раньше требовало delete_messages (см. историю
    GatewayConsumer._pin_message) — теперь у него собственное право
    pin_messages со стандартным default=False. Без этого шага роли, которые
    УЖЕ умели закреплять, молча потеряли бы эту возможность при накатывании
    миграции. Остальные новые права выставлены дефолтами так, что поведение
    существующих ролей не меняется, и переносить там нечего."""
    apps.get_model("chat", "Role").objects.filter(
        delete_messages=True).update(pin_messages=True)


def noop(apps, schema_editor):
    """Откат: pin_messages просто исчезает вместе с колонкой (AddField
    реверсится в RemoveField), отдельно ничего восстанавливать не нужно."""


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_friendnickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slowmode_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='add_reactions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='attach_files',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='ban_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='bypass_slowmode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='change_nickname',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='connect',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='create_expressions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='create_invites',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='manage_expressions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='pin_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='read_message_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='request_screen_share',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='start_mute_vote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='use_external_emojis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='use_external_stickers',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(carry_over_pin_permission, noop),
    ]
