# Generated by Django 5.0.7 on 2026-08-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_channel_slowmode_seconds_membership_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='allowed_channels', to='chat.role'),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
