# Generated by Django 5.0.6 on 2026-08-02 15:45

import chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_channel_allowed_roles_channel_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerEmoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('file_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(max_length=300, upload_to=chat.models.emoji_upload_to)),
                ('static_file', models.FileField(blank=True, max_length=300, upload_to=chat.models.emoji_upload_to)),
                ('animated', models.BooleanField(default=False)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emoji', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji', to='chat.server')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='serveremoji',
            constraint=models.UniqueConstraint(fields=('server', 'name'), name='unique_server_emoji_name'),
        ),
    ]
