# Generated by Django 5.0.6 on 2026-08-03 10:54

import chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_owner_role_expressions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sticker_packs', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sticker_packs', to='chat.server')),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('file_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(max_length=300, upload_to=chat.models.sticker_upload_to)),
                ('static_file', models.FileField(blank=True, max_length=300, upload_to=chat.models.sticker_upload_to)),
                ('format', models.CharField(default='webp', max_length=8)),
                ('animated', models.BooleanField(default=False)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stickers', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='chat.stickerpack')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='stickerpack',
            constraint=models.UniqueConstraint(fields=('server', 'name'), name='unique_server_sticker_pack'),
        ),
        migrations.AddConstraint(
            model_name='stickerpack',
            constraint=models.UniqueConstraint(condition=models.Q(('server__isnull', True)), fields=('name',), name='unique_default_sticker_pack'),
        ),
    ]
