# Generated by Django 5.0.6 on 2026-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_stickerpack_sticker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='voice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='waveform',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='role',
            name='send_voice_messages',
            field=models.BooleanField(default=True),
        ),
    ]
