# Generated by Django 5.0.6 on 2026-08-04 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_channelreadstate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_private_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='invites_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_spoiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.CreateModel(
            name='ChannelMemberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_level', models.CharField(choices=[('default', 'Как на сервере'), ('all', 'Все сообщения'), ('mentions', 'Только упоминания'), ('none', 'Ничего')], default='default', max_length=10)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('muted_forever', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_settings', to='chat.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='channelmembersettings',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='unique_channel_member_settings'),
        ),
    ]
