# Generated by Django 5.0.6 on 2026-08-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_channel_allowed_users_channel_invites_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='age_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
