# Generated by Django 5.0.6 on 2026-08-06 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_channel_age_restricted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='join_invite_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='membership',
            name='join_invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='join_method',
            field=models.CharField(choices=[('unknown', 'Неизвестно'), ('public', 'Открытый сервер'), ('invite_link', 'Ссылка-приглашение'), ('invite_direct', 'Личное приглашение'), ('request', 'Одобренная заявка'), ('owner', 'Создатель сервера')], default='unknown', max_length=20),
        ),
        migrations.CreateModel(
            name='ServerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('join', 'Вступление'), ('leave', 'Выход'), ('kick', 'Кик'), ('ban', 'Бан'), ('unban', 'Разбан'), ('role_add', 'Выдана роль'), ('role_remove', 'Снята роль'), ('nickname', 'Смена никнейма')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='chat.server')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['server', 'target', '-created_at'], name='chat_server_server__8414f7_idx')],
            },
        ),
    ]
