# Generated by Django 5.0.6 on 2026-08-08 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_channel_archived_channel_created_by_channel_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='invite_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='system_kind',
            field=models.CharField(blank=True, choices=[('thread_created', 'Создана ветка')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='system_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creation_notices', to='chat.channel'),
        ),
        migrations.CreateModel(
            name='ThreadMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_members', to='chat.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='threadmember',
            constraint=models.UniqueConstraint(fields=('user', 'thread'), name='unique_thread_member'),
        ),
    ]
