# Generated by Django 5.0.6 on 2026-08-09 22:09

import chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_poll_polloption_pollvote_poll_poll_single_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundboardSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('emoji', models.CharField(blank=True, default='', max_length=8)),
                ('file_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content_type', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=300, upload_to=chat.models.sound_upload_to)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sounds', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='chat.server')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='soundboardsound',
            constraint=models.UniqueConstraint(fields=('server', 'name'), name='soundboard_name_unique_per_server'),
        ),
    ]
