# Generated by Django 5.0.7 on 2026-07-31 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('js_runtime', 'JS — необработанное исключение'), ('render', 'React — ошибка рендера'), ('promise', 'Promise — необработанный reject'), ('api', 'API — неуспешный ответ'), ('voice_webrtc', 'Голос / WebRTC'), ('websocket', 'WebSocket — шлюз'), ('manual', 'Отправлено кодом вручную')], default='js_runtime', max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('culprit', models.CharField(blank=True, help_text='Верхний кадр стека — где именно это произошло.', max_length=200, verbose_name='Место')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('investigating', 'Разбираемся'), ('resolved', 'Исправлена'), ('ignored', 'Игнорируем')], default='new', max_length=20, verbose_name='Статус')),
                ('times_seen', models.PositiveIntegerField(default=0, verbose_name='Событий')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Впервые')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний раз')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Исправлена в')),
            ],
            options={
                'verbose_name': 'Ошибка (группа)',
                'verbose_name_plural': 'Ошибки',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['-last_seen'], name='bugs_errorg_last_se_574322_idx'), models.Index(fields=['status', '-last_seen'], name='bugs_errorg_status_770030_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('web_desktop', 'Веб — ПК'), ('web_mobile', 'Веб — мобильный'), ('desktop_app', 'Приложение — ПК'), ('mobile_app', 'Приложение — мобильное'), ('unknown', 'Неизвестно')], default='unknown', max_length=20, verbose_name='Платформа')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('stack', models.TextField(blank=True, verbose_name='Стек')),
                ('route', models.CharField(blank=True, max_length=500, verbose_name='Экран')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='User-Agent')),
                ('app_version', models.CharField(blank=True, max_length=60, verbose_name='Версия сборки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bugs.errorgroup')),
            ],
            options={
                'verbose_name': 'Событие ошибки',
                'verbose_name_plural': 'События ошибок',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='bugs_errore_created_bb49be_idx'), models.Index(fields=['group', '-created_at'], name='bugs_errore_group_i_5e417f_idx')],
            },
        ),
    ]
