# Generated by Django 5.0.7 on 2026-07-31 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Что произошло')),
                ('steps', models.TextField(blank=True, verbose_name='Что к этому привело')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('answered', 'Отвечено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='Заметка (не видна автору)')),
                ('platform', models.CharField(choices=[('web_desktop', 'Веб — ПК'), ('web_mobile', 'Веб — мобильный'), ('desktop_app', 'Приложение — ПК'), ('mobile_app', 'Приложение — мобильное'), ('unknown', 'Неизвестно')], default='unknown', max_length=20, verbose_name='Платформа')),
                ('route', models.CharField(blank=True, max_length=500, verbose_name='Экран')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='User-Agent')),
                ('app_version', models.CharField(blank=True, max_length=60, verbose_name='Версия сборки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('related_groups', models.ManyToManyField(blank=True, related_name='bug_reports', to='bugs.errorgroup', verbose_name='Связанные ошибки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='support_bug_status_6a138a_idx'), models.Index(fields=['-created_at'], name='support_bug_created_9525ff_idx')],
            },
        ),
    ]
