# Generated by Django 5.0.6 on 2026-07-25 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original', models.ImageField(editable=False, upload_to='favicons')),
                ('is_default', models.BooleanField(default=False, verbose_name='Стандартная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружена')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_favicons', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Favicon',
                'verbose_name_plural': 'Favicons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='favicon',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_favicon'),
        ),
    ]
